run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: errorf
        severity: warning
  goimports:
    local-prefixes: github.com/avito-tech/pr-reviewer-service

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

